mkdir ../data_centre/databases
touch ../data_centre/databases/r2.db
touch ../data_centre/databases/mse.db
touch ../data_centre/databases/qlike.db
touch ../data_centre/databases/coefficients.db
touch ../data_centre/databases/tstats.db
touch ../data_centre/databases/pvalues.db
touch ../data_centre/databases/performance.db
touch ../data_centre/databases/rolling_metrics.db
